version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Required
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Security
    - gosec
    - noctx
    - bodyclose
    - sqlclosecheck
    # Error handling
    - errorlint
    - errchkjson
    - wastedassign
    # Best practices
    - gocritic
    - revive
    - unconvert
    - dupl
    - goconst
    - misspell
    - prealloc
    - copyloopvar

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - govet
